### PR TITLE
added timer for breathing exercise

### PR DESCRIPTION
**Pull request by agnijeetsharma**
@Bluesparx i have added Timer for breathing exercise in which user can reset and pause the excercise and if user pause the exercise then it will start from where he/she left

Kindly merge My PR and most important label as hacktoberfest

Thanks

I have attached the video of the same

Uploading bandicam 2024-10-13 14-04-33-625.mp4…

### CODE REVIEW

**Comment by agnijeetsharma** [comment]
@Riddhi050803  @Bluesparx #issue50

**Comment by agnijeetsharma** [comment]
@Bluesparx there might be merge conflicts which can be resolved

**Comment by Riddhi050803** [comment]
Could you please upload the video again? We are not able to see it. @agnijeetsharma

**Comment by agnijeetsharma** [comment]
@Riddhi050803 sure 


Uploading bandicam 2024-10-13 14-04-33-625.mp4…

**Comment by agnijeetsharma** [comment]
https://github.com/user-attachments/assets/a071780b-4f5b-4949-b383-decad192502d

**Comment by agnijeetsharma** [comment]
@Riddhi050803 any update

**Pull request merged**
