### PR TITLE
ADDED GET STARTED BUTTON TO HOMESCREEN

### PR DESCRIPTION
**Pull request by PRAteek-singHWY**
Get started button to home screen has been added and it redirects the user to register page.

### CODE REVIEW

**Comment by PRAteek-singHWY** [comment]
@Riddhi050803 ma'am can u please review the Get Started button on Homescreen ,
this issue has been resolved

**Comment by Bluesparx** [comment]
Could you pls add screenshots as well.

**Comment by PRAteek-singHWY** [comment]
> Could you pls add screenshots as well.

sure sir i am adding screen shots 

> Could you pls add screenshots as well.

Maintainers i have added the screenshots
1-> the Get Started button
2-> the Get Started button with hover effect
3-> the Get Started button redirects to Register page

Screenshot 2024-10-09 at 19 52 44
Screenshot 2024-10-09 at 19 52 49
Screenshot 2024-10-09 at 19 52 53


@Bluesparx  Please review the changes

Thank You

**Comment by Bluesparx** [comment]
Hey, looks good but just a slight change but could you please make it violet like the other pages, so that it matches the overall theme. 
Just let me know when you've done it. I'll merge the PR.

**Comment by Bluesparx** [comment]
@PRAteek-singHWY you have not handled authentication like we have done for navbar. It's visible in home page even after logging in, so I'm reverting this.

**Pull request merged**
