### PR TITLE
Made responsive

### PR DESCRIPTION
**Pull request by Aditya-NV-06**
can you add hacktoberfest accepted tag in the repo

### CODE REVIEW

**Comment by Riddhi050803** [comment]
Please attach screenshots for every page you have made responsive.  @Aditya-NV-06

**Comment by Aditya-NV-06** [comment]
Ok

**Comment by Aditya-NV-06** [comment]
how can I get the env values for the frontend

**Comment by Bluesparx** [comment]
You have to create ur firebase account

**Comment by Aditya-NV-06** [comment]
i created

**Pull request closed without merging**
